### ISSUE TITLE
Uncaught Error: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by johnsmith025** [amarjeetpatidar007/certifications-web#4]
Sign in With Google Not Working 

![image](https://github.com/user-attachments/assets/80e05684-eb39-4eaf-ac84-3eb3b7cee70f)

Uncaught Error: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

main.dart.js:5586 Uncaught Error: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.registerIdTokenListener"., null, null)

**Comment by amarjeetpatidar007** [comment]
Hi @johnsmith025,

Thank you for bringing this issue to my attention!

I am already aware of the problem and will address it in the next commit.

Thank you for your patience.

Regards,
Amarjeet
